// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package accounting_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountingTransaction struct {
	ID                          string
	ProjectID                   pgtype.Text
	AccountingTransactionTypeID int32
	Memo                        pgtype.Text
	PostingDate                 pgtype.Timestamptz
	UpdatedBy                   pgtype.Text
	UpdatedAt                   pgtype.Timestamptz
	CreatedBy                   string
	CreatedAt                   pgtype.Timestamptz
}

type AccountingTransactionType struct {
	AccountingTransactionTypeID int32
	Name                        string
}

type LedgerAccount struct {
	LedgerAccountID        int32
	Description            pgtype.Text
	AccountCode            pgtype.Text
	TaxCode                pgtype.Text
	Name                   string
	LedgerAccountClassID   int32
	LedgerAccountTypeID    int32
	LedgerAccountSubTypeID int32
	LedgerAccountLevel     int32
	LedgerAccountParentID  pgtype.Text
	UpdatedBy              pgtype.Text
	UpdatedAt              pgtype.Timestamptz
	CreatedBy              string
	CreatedAt              pgtype.Timestamptz
}

type LedgerAccountClass struct {
	LedgerAccountClassID int32
	Name                 string
}

type LedgerAccountSubType struct {
	LedgerAccountSubTypeID int32
	Name                   string
}

type LedgerAccountType struct {
	LedgerAccountTypeID int32
	Name                string
}
