// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package accounting_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountingTransaction struct {
	ID                string
	ProjectID         pgtype.Text
	TransactionTypeID int32
	AccountNumber     pgtype.Text
	Memo              pgtype.Text
	PostingDate       pgtype.Timestamptz
	UpdatedBy         pgtype.Text
	UpdatedAt         pgtype.Timestamp
	CreatedBy         string
	CreatedAt         pgtype.Timestamp
}

type AccountingTransactionType struct {
	ID   int32
	Name string
}
